resource_group_name      = "martinzexampleResourceGroup3"
location                 = "West US"
virtual_network_name     = "myVNet3"
address_space            = ["10.0.0.0/25"]
public_subnet_prefix     = ["10.0.0.0/27"]
private_subnet_prefix    = ["10.0.0.64/27"]
key_vault_name           = "martinzKeyVault3"
app_service_plan_name    = "exampleAppServicePlan"
app_service_name         = "martinzexampleAppService3"
sql_server_name          = "martinzexamplesqlserver3"
