name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # Default permission

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login to Azure using Service Principal
      - name: Login to Azure using Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Use the credentials stored in GitHub secrets

      # Initialize Terraform (this automatically uses the Azure credentials set by the login action)
      - name: Terraform Init
        run: terraform init

      # Run Terraform Plan (optional but useful for debugging)
      - name: Terraform Plan
        run: terraform plan

      # Apply Terraform changes
      - name: Terraform Apply
        run: terraform apply -auto-approve
