name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read  # Default permission.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure using Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Service Principal credentials in JSON format
          auth-type: SERVICE_PRINCIPAL  # Ensure using Service Principal authentication

      - name: Terraform Init (with backend config)
        run: terraform init \
          -backend-config="subscription_id=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" \
          -backend-config="client_id=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" \
          -backend-config="client_secret=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" \
          -backend-config="tenant_id=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve
